rm(list=ls())
#library(ggbiplot)
library(data.table)
data=data.frame(read.table('RSEM.genes.fpkm.gt1.tsv',header=TRUE,sep='\t'))
data$GeneName=NULL
data$TranscriptID=NULL
data$GeneID=NULL
data.pca=prcomp(t(data),center=FALSE,scale=FALSE)
labelvals=as.character(round(100*data.pca$sdev^2/sum(data.pca$sdev^2),2))
png('genes_PCA_variance_explained.png') 
barplot(100*data.pca$sdev^2/sum(data.pca$sdev^2),las=2,ylab="% Variance Explained",xlab="Principal Component",ylim=c(0,100))
text(1:12,100*data.pca$sdev^2/sum(data.pca$sdev^2),labels=labelvals,pos=3,cex=1)
dev.off() 

groups=factor(rownames(data.pca$x))
control_treated_groups=factor(c(1,1,1,2,2,2,1,1,1,2,2,2))
health_groups=factor(c(1,1,1,1,1,1,2,2,2,2,2,2))
rep_groups=factor(c(1,1,1,2,2,2,3,3,3,4,4,4))

plot(data.pca$x[,c(1,2)],col=rep_groups,pch=16)
text(data.pca$x[,c(1,2)],labels=groups,pos=3,cex=1)
title("PC1 vs PC2")
plot(data.pca$x[,c(1,3)],col=rep_groups,pch=16)
text(data.pca$x[,c(1,3)],labels=groups,pos=3,cex=1)
title("PC1 vs PC3")
plot(data.pca$x[,c(2,3)],col=rep_groups,pch=16)
text(data.pca$x[,c(2,3)],labels=groups,pos=3,cex=1)
title("PC2 vs PC3")
plot(data.pca$x[,c(2,4)],col=rep_groups,pch = 16)
text(data.pca$x[,c(2,4)],labels=groups,pos=3,cex=1)
title("PC2 vs PC4")
plot(data.pca$x[,c(2,5)],col=rep_groups,pch = 16)
text(data.pca$x[,c(2,5)],labels=groups,pos=3,cex=1)
title("PC2 vs PC5") 
#################################### JUST MDX ##############################################
mdx=subset(data,select=c("MDX_1R","MDX_2R","MDX_3R","MDX_1L","MDX_2L","MDX_3L"))

mdx.pca=prcomp(t(mdx),center=FALSE,scale=FALSE)
labelvals=as.character(round(100*mdx.pca$sdev^2/sum(mdx.pca$sdev^2),2))
png('genes_PCA_variance_explained_MDX_only.png') 
barplot(100*mdx.pca$sdev^2/sum(mdx.pca$sdev^2),las=2,ylab="% Variance Explained",xlab="Principal Component for MDX",ylim=c(0,100))
text(1:12,100*mdx.pca$sdev^2/sum(mdx.pca$sdev^2),labels=labelvals,pos=3,cex=1)
dev.off() 

groups=factor(rownames(mdx.pca$x))
control_treated_groups=factor(c(1,1,1,2,2,2))
rep_groups=factor(c(3,3,3,4,4,4))

plot(mdx.pca$x[,c(1,2)],col=rep_groups,pch=16)
text(mdx.pca$x[,c(1,2)],labels=groups,pos=3,cex=1)
title("PC1 vs PC2 MDX ONLY")
plot(mdx.pca$x[,c(1,3)],col=rep_groups,pch=16)
text(mdx.pca$x[,c(1,3)],labels=groups,pos=3,cex=1)
title("PC1 vs PC3 MDX ONLY")
plot(mdx.pca$x[,c(2,3)],col=rep_groups,pch=16)
text(mdx.pca$x[,c(2,3)],labels=groups,pos=3,cex=1)
title("PC2 vs PC3 MDX ONLY")

#################################### JUST WT ##############################################
wt=subset(data,select=c("WT_1R","WT_2R","WT_3R","WT_1L","WT_2L","WT_3L"))
wt.pca=prcomp(t(wt),center=FALSE,scale=FALSE)
labelvals=as.character(round(100*wt.pca$sdev^2/sum(wt.pca$sdev^2),2))
png('genes_PCA_variance_explained_WT_only.png') 
barplot(100*wt.pca$sdev^2/sum(wt.pca$sdev^2),las=2,ylab="% Variance Explained",xlab="Principal Component for WT",ylim=c(0,100))
text(1:12,100*wt.pca$sdev^2/sum(wt.pca$sdev^2),labels=labelvals,pos=3,cex=1)
dev.off() 

groups=factor(rownames(wt.pca$x))
control_treated_groups=factor(c(1,1,1,2,2,2))
rep_groups=factor(c(1,1,1,2,2,2))

plot(wt.pca$x[,c(1,2)],col=rep_groups,pch=16)
text(wt.pca$x[,c(1,2)],labels=groups,pos=3,cex=1)
title("PC1 vs PC2 WT ONLY")
plot(wt.pca$x[,c(1,3)],col=rep_groups,pch=16)
text(wt.pca$x[,c(1,3)],labels=groups,pos=3,cex=1)
title("PC1 vs PC3 WT ONLY")
plot(wt.pca$x[,c(2,3)],col=rep_groups,pch=16)
text(wt.pca$x[,c(2,3)],labels=groups,pos=3,cex=1)
title("PC2 vs PC3 WT ONLY")
