cp /nas/homes/annashch/Age_ATAC/outputs/d0_Young/cromwell-executions/atac/e373e737-4927-458b-b2cb-023ed08dd76e/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d0_Young.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/outputs/d1_Aged/cromwell-executions/atac/4eab35c7-3cb6-4836-834a-52aaf44300ce/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d1_Aged.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/outputs/d1_Young/cromwell-executions/atac/ae7e0583-b599-4f9d-b576-2d894bf69b5f/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d1_Young.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/outputs/d5_Aged/cromwell-executions/atac/cd51b1d5-c953-45a0-84e2-7c98de55808b/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d5_Aged.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/outputs/d5_Young/cromwell-executions/atac/13ba4ec6-4586-4521-bbb8-a9f5cca58858/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d5_Young.optimal_peak.narrowPeak.hammock.gz.tbi 
cp /nas/homes/annashch/Age_ATAC/outputs/d7_Young/cromwell-executions/atac/e3042974-4252-4c53-85a4-e2f8a3af880d/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d7_Young.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/caper_out/atac/b4245fba-248f-4201-bd66-907bb8e97a85/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d0_Aged.optimal_peak.narrowPeak.hammock.gz.tbi 
cp /nas/homes/annashch/Age_ATAC/caper_out/atac/c90f9517-fbd5-4d41-99b6-83a7a19fb0c6/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d3_Aged.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/caper_out/atac/0956918d-8f9f-4836-aaab-4bb310d915b9/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d3_Young.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/caper_out/atac/edc38b87-7126-46ab-89a2-2e6afa43eee7/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi D0_Pax7_Young.optimal_peak.narrowPeak.hammock.gz.tbi
cp /nas/homes/annashch/Age_ATAC/caper_out/atac/5b411aaf-f251-4362-9893-918cbf092061/call-reproducibility_overlap/execution/optimal_peak.narrowPeak.hammock.gz.tbi d7_Aged.optimal_peak.narrowPeak.hammock.gz.tbi

